=== 概述

经常需要使用java对象的属性来封装程序的数据，每次都使用反射技术完成此类操作过于麻烦，所以sun公司开发了一套API，专门用于操作java对象的属性。

内省(IntroSpector)是Java语言对JavaBean 类属性、事件的一种处理方法。 例如类A中有属性name,那我们可以通过getName,setName 来得到其值或者设置新的值。 通过getName/setName 来访问name属性，这就是默认的规则。

Java中提供了一套API 用来访问某个属性的getter/setter方法，通过这些API可以使你不需要了解这个规则，这些API存放于包java.beans 中。

一般的做法是通过类Introspector的getBeanInfo方法获取某个对象的BeanInfo信息,然后通过BeanInfo来获取属性的描述器(PropertyDescriptor),通过这个属性描述器就可以获取某个属性对应的getter/setter方法,然后我们就可以通过反射机制来调用这些方法。

我们又通常把javabean的实例对象称之为值对象，因为这些bean中通常只有一些信息字段和存储方法，没有功能性方法。

一个JavaBean类可以不当JavaBean用，而当成普通类用。JavaBean实际就是一种规范，当一个类满足这个规范，这个类就能被其它特定的类调用。一个类被当作javaBean使用时，JavaBean的属性是根据方法名推断出来的，它根本看不到java类内部的成员变量。去掉set前缀，然后取剩余部分，如果剩余部分的第二个字母是小写的，则把剩余部分的首字母改成小的。

内省访问JavaBean有两种方法：
通过PropertyDescriptor来操作Bean对象

[source, java]
----
public class Test {
    public static void demo1() throws Exception {
        User user = new User("zhangsan", 21);
        String propertyName = "name";
        // 直接指定要访问的属性
        PropertyDescriptor pd = new PropertyDescriptor(propertyName, user.getClass());
        // 获取到读方法
        Method readMethod = pd.getReadMethod();
        // 反射机制调用
        Object invoke = readMethod.invoke(user, null);
        System.out.println("名字：" + invoke);
        pd.getWriteMethod().invoke(user, "lisi");
        invoke = readMethod.invoke(user, null);
        System.out.println("名字：" + invoke);
    }
}
----

通过Introspector类获得Bean对象的 BeanInfo，然后通过 BeanInfo 来获取属性的描述器（ PropertyDescriptor ），通过这个属性描述器就可以获取某个属性对应的 getter/setter 方法，然后通过反射机制来调用这些方法。

[source, java]
----
public class Test {
  public static void demo2() throws Exception {
    // 获取整个Bean的信息
    // BeanInfo beanInfo= Introspector.getBeanInfo(user.getClass());
    // 在Object类时候停止检索，可以选择在任意一个父类停止
    BeanInfo beanInfo = Introspector.getBeanInfo(user.getClass(), Object.class);

    System.out.println("所有属性描述：");
    // 获取所有的属性描述
    PropertyDescriptor[] pds = beanInfo.getPropertyDescriptors();
    for (PropertyDescriptor propertyDescriptor : pds) {
        System.out.println(propertyDescriptor.getName());
    }
    System.out.println("所有方法描述：");
    for (MethodDescriptor methodDescriptor : beanInfo.getMethodDescriptors()) {
      System.out.println(methodDescriptor.getName());
      // Method method = methodDescriptor.getMethod();
    }
  }
}
----

[source, java]
----
public class User {
    private String name;
    private int age;
    public User(String name, int age) {
      this.name = name;
      this.age = age;
    }
    public String getName() {
      return name;
    }
    public void setName(String name) {
      this.name = name;
    }
    public int getAge() {
      return age;
    }
    public void setAge(int age) {
      this.age = age;
    }
}
----


=== 内省->了解JavaBean

JavaBean是一种特殊的Java类，主要用于传递数据信息，这种java类中的方法主要用于访问私有的字段，且方法名符合某种命名规则。

如果要在两个模块之间传递多个信息，可以将这些信息封装到一个JavaBean中，这种JavaBean的实例对象通常称之为值对象（Value Object   简称VO）。这些信息再类中用私有字段来存储，如果读取或设置这些字段的值则需要通过一些相应的方法来访问，JavaBean的属性是根据其中的setter和getter发方法来确定的，而不是根据其中的成员变量。如果方法名为setId,中文疑似就是设置id。

总之，一个类被当作javaBean使用时，JavaBean的属性是根据方法名推断出来的，他根本看不到java类内部的成员变量。

一个符合JavaBean特点的类可以那个做普通类一样镜像使用，但把他当作JavaBean用肯定需要带来一些额外的好处，我们才会去了解和应用JavaBean。好处如下：

* 在JavaEE开发中，经常要使用到JavaBean。很多环境要求按JavaBean方式进行操作，别人都这么用和要求这个做
* JDK中提供了对JavaBean进行操作的一些API，这套API就成为内省。如果要你自己去通过getX方法来访问私有的x,用内省这套api操作JavaBean比用普通类的方式更方便。

=== 内省的综合案例

[source,java]
----
import haiyang.yu.reflect.ReflectPoint;

import java.beans.BeanInfo;
import java.beans.IntrospectionException;
import java.beans.Introspector;
import java.beans.PropertyDescriptor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class App {

    public static void main( String[] args ) throws Exception {
        ReflectPoint pt1 = new ReflectPoint(3, 5);

        String propertyName = "x";
        Object retVal = getProperty(pt1, propertyName);
        System.out.println(retVal);

        Object propertyValue = 7;
        setProperty(pt1, propertyName, propertyValue);

        System.out.println(pt1.getX());
        System.out.println(getProperty2(pt1, propertyName));
    }


    /**使用字符串拼写方法名进行反射1*/

    /** 使用PropertyDescriptor 对象的方式设置JavaBean的属性3*/
    private static void setProperty(Object pt1, String propertyName, Object propertyValue) throws IntrospectionException, IllegalAccessException, InvocationTargetException {
        PropertyDescriptor pd1 = new PropertyDescriptor(propertyName, pt1.getClass());
        // 获取set方法
        Method writeMethod = pd1.getWriteMethod();
        writeMethod.invoke(pt1,propertyValue);
    }

    /** 使用PropertyDescriptor 对象的方式获取JavaBean的属性*/
    private static Object getProperty(ReflectPoint pt1, String propertyName) throws IntrospectionException, IllegalAccessException, InvocationTargetException {
        PropertyDescriptor pd = new PropertyDescriptor(propertyName, pt1.getClass());
        // 获取get方法
        Method readMethod = pd.getReadMethod();
        return readMethod.invoke(pt1);
    }

    /**
     * 2
     * 采用遍历BeanInfo的所有属性方式来查找和设置某个对象的属性。
     * 在程序中把一个类当做JavaBean来看，就是调用Introspector.getBeanInfo方法，
     * 得到的BeanInfo对象封装了把这个类当做JavaBean看的结果信息。
     */
    private static Object getProperty2(ReflectPoint pt1, String propertyName) throws IntrospectionException, IllegalAccessException, InvocationTargetException {
        BeanInfo beanInfo = Introspector.getBeanInfo(pt1.getClass());
        PropertyDescriptor[] propertyDescriptors = beanInfo.getPropertyDescriptors();
        Object retVal = null;
        for (PropertyDescriptor pd: propertyDescriptors){
            if(pd.getName().equals(propertyName)){
                Method readMethod = pd.getReadMethod();
                retVal = readMethod.invoke(pt1);
                break;
            }
        }

        return retVal;
    }
}
----

=== BeanUtils工具包

引入相关的jar包依赖
[source,xml]
----
<dependency>
    <groupId>commons-beanutils</groupId>
    <artifactId>commons-beanutils</artifactId>
    <version>1.9.3</version>
</dependency>
----
- 用BeanUtils类先get原来设置好的属性，再将其set为一个新值。
* get属性是返回的结果为字符串，set属性是可以接受任意类型的对象，通常使用字符串。
- 用PropertyUtils类先get原来设置好的属性，再将其set为一个新值。
* get属性是放回结果为该属性本来的类型，set属性时只接受该属性本来的类型。

BeanUtils不仅可以操作JavaBean，还可以做Map和JavaBean之间的转换

[source,java]
----
public class Test {
  public static void main( String[] args ) throws Exception {
    ReflectPoint pt1 = new ReflectPoint(3, 5);

    String x = BeanUtils.getProperty(pt1, "x");
    System.out.println(x);
    // 无须关注数据的具体类型，他会自动的将其转换成相应的属性的类型
    BeanUtils.setProperty(pt1, "x", "9");
    System.out.println(pt1.getX());

    // birthday是一个复合对象，BeanUtils是支持级联操作的
    BeanUtils.setProperty(pt1, "birthday.time", "111");
    // String property = BeanUtils.getProperty(pt1, "birthday.time");
    // System.out.println(property);

    // BeanUtils是以字符串的形式操作的，而PropertyUtils是以字段本身的类型进行操作的。
    PropertyUtils.setProperty(pt1, "x", 9);
    System.out.println(PropertyUtils.getProperty(pt1, "x").getClass());

  }
}
----
